DROP TABLE IF EXISTS screenshots CASCADE;
DROP TABLE IF EXISTS cases CASCADE;
DROP TABLE IF EXISTS platform_accounts CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP INDEX IF EXISTS screenshots_case_id_idx;
DROP INDEX IF EXISTS screenshots_case_type_unique;
DROP INDEX IF EXISTS screenshots_object_key_unique;
DROP INDEX IF EXISTS screenshots_pkey;
DROP INDEX IF EXISTS cases_query_time_idx;
DROP INDEX IF EXISTS cases_revision_idx;
DROP INDEX IF EXISTS cases_client_uid_unique;
DROP INDEX IF EXISTS cases_pkey;
DROP INDEX IF EXISTS platform_accounts_enabled_idx;
DROP INDEX IF EXISTS platform_accounts_label_unique;
DROP INDEX IF EXISTS platform_accounts_pkey;
DROP INDEX IF EXISTS sessions_user_id_idx;
DROP INDEX IF EXISTS sessions_token_hash_unique;
DROP INDEX IF EXISTS sessions_pkey;
DROP INDEX IF EXISTS users_username_unique;
DROP INDEX IF EXISTS users_pkey;
DROP SEQUENCE IF EXISTS cases_revision_seq;
